### PR TITLE
Add Docker and REX-Ray install and config for ScaleIO

### PR DESCRIPTION
**Pull request by jonasrosland**
Installs and configures Docker, REX-Ray and libStorage to work with the ScaleIO cluster.

Signed-off-by: Jonas Rosland jonas.rosland@emc.com

### CODE REVIEW

**Comment by kacole2** [comment]
👍  LGTM

**Comment by jonasrosland** [comment]
Thanks for testing it out @kacole2, @cduchesne and @clintonskitson, merging.

**Comment by vtexan** [comment]
ahem - i tested it too !!

**Comment by clintkitson** [comment]
Well done @vtexan, `vagrant up` that thing =)

**Comment by vtexan** [comment]
i was the first to see if it worked !

**Comment by jonasrosland** [comment]
It's true, thank you @vtexan :)

**Comment by vtexan** [comment]
Huge thanks to @jonasrosland for helping me and Brian Verkley get our project working with these changes !  WOOOT !!!!

**Pull request merged**
